### ISSUE TITLE
Proposal Revision 3

### ISSUE THREAD

**Issue by code259** [code259/sprint4_frontend#17]
### Overview
- Ten-word overview: Chess social platform to discuss, analyze and learn chess content.
- Our project will be a social media website and forum where users can discuss chess topics and interact with Artificial Intelligence to learn and play chess.
- Our project is based on the flocker project and will utilize numerous elements such as the posting and post database, user authentication and database, and external APIs pertaining to chess. For the posts specifically, we will require an upload system that will be based on the pfp storage system, and we will likely need to create a new API endpoint for the storage system. 
- Our initial discussion for Sprint 4: https://github.com/code259/sprint4_frontend/issues/1#issue-2677335072

### Repositories
- https://github.com/code259/sprint4_backend
- https://github.com/code259/sprint4_frontend

### Standups
- Standup 1: https://github.com/code259/sprint4_frontend/issues/5#issue-2713519425
- Standup 2: https://github.com/code259/sprint4_frontend/issues/6#issue-2716033005
- Standup 3: https://github.com/code259/sprint4_frontend/issues/14#issue-2718887652
- Standup 4: #15 

### Video Planning
- Add Video planning here
- add subtasks to issues (checkboxes)

### Future Steps
- finish burndown

### Pages
- Landing Page: 
   - Since our project is a social media website, we will have landing page to inform new visitors of the purpose of the website and to redirect to various pages. 
   - It will utilize Javascript animations (GSAP) to improve visual interest and is based on design inspiration to create a visually appealing design.
- Home Page: 
    - After login and authentication the user will go to a home page with a list of posts by all users, of chess related topics such as certain board positions, tactics, questions, etc. 
    - User will be able to view the post and interact with the posts by having commenting capabilities, which will likely be shown in a modal. 
    - Will have various filter methods to see different topics "strategy", "tactics", "social" etc.
- Chat Page: 
    - Will have a chess board where users can interact with Gemini or other LLM to talk and learn about chess.
    - Will have the ability to view past chats, as messages will be saved and images can be sent to API as well for deeper conversation and learning
- Game Page: 
    - Will create a page where users can use a real chess board to play against a bot, which will be created through various Chess APIs. 
    - The bot will be powered by the Gemini API, and we plan on being able to save games which enables deeper post discussion in the main post feed section.

### Project Structure
<img width="1159" alt="Screenshot 2024-12-04 at 3 53 42 PM" src="https://github.com/user-attachments/assets/8598b23b-c1b4-43e6-99f7-88fa284e0f6d">

### Tasks & Roles
Note: Groups not finalized until Add/Drop deadline. 
- **_Scrum Master: Nikhil Maturi_**
   - (Backend Developer) Backend Integration with REST API for Post Channels, Upload API Endpoint and Overview
   - Story & Feature: https://github.com/code259/sprint4_frontend/issues/11#issue-2718516041

- Developer 1: Vasanth Rajasekaran
   - (Backend Developer) Backend Integration with REST API (CRUD Requests) for Chat Room
   - Story & Feature: https://github.com/code259/sprint4_frontend/issues/10#issue-2716092197

- Developer 2: Aarush Gowda 
   - (Backend Developer) Backend Integration with Chess APIs, and managing game aspect of the project.
   - Story & Feature: https://github.com/code259/sprint4_frontend/issues/13#issue-2718807105

- **_Assistant Scrum Master: Mihir Thaha_**
   - (Frontend Developer) Landing Page Design and Development and Dynamic Page Load based on Authentication
   - Story & Feature: https://github.com/code259/sprint4_frontend/issues/7#issue-2716052881

- Developer 1: Nikhil Narayan
   - (Frontend Developer) Landing Page Design and Development, UML, and Javascript for Modal Design
   - Story & Feature: https://github.com/code259/sprint4_frontend/issues/8#issue-2716074402

- Developer 2: Jowan Elzein 
   - (Frontend Developer) Landing Page Design and Development, Javascript for Animations (GSAP)
   - Story & Feature: https://github.com/code259/sprint4_frontend/issues/9#issue-2716090220

### Visual Design

<img width="571" alt="Screenshot 2024-12-02 at 1 33 23 PM" src="https://github.com/user-attachments/assets/9fb4a86f-ab68-4396-b931-06a6d942002a">

<img width="677" alt="Screenshot 2024-12-02 at 1 32 45 PM" src="https://github.com/user-attachments/assets/b5856de5-23db-47ae-973c-d6face2fb3c5">

### Next Steps (For Checkpoint 1)
List of future ideas: https://github.com/code259/sprint4_frontend/issues/2#issue-2677357558
- [x] Create Kanban Board to track iterations and features. 
- [ ] Utilize PEP 8 Guideline for Code (https://peps.python.org/pep-0008/#introduction)
- [ ] Use UML or planning methods to show plan for integration of new ideas and features from Flocker.
- [x] Create visually appealing Homepage - create brief design using figma
- [ ] Remove redundancy in other pages and create good UX.
- [x] Remove features from Flocker not required for our project.
- [ ] Implement API requests to LLM (AI Model), sending image data.
