### ISSUE TITLE
Pre Turkey Update

### ISSUE THREAD

**Issue by code259** [code259/sprint4_frontend#3]
### Overview
- Our project will be a social media website and forum where users can discuss chess topics and interact with Artificial Intelligence to learn and play chess.
- Our project is based on the flocker project and will utilize numerous elements such as the posting and post database, user authentication and database, and external APIs pertaining to chess. For the posts specifically, we will require an upload system that will be based on the pfp storage system, and we will likely need to create a new API endpoint for the storage system. 
- Our initial discussion for Sprint 4: https://github.com/code259/sprint4_frontend/issues/1#issue-2677335072

### Repositories
- https://github.com/code259/sprint4_backend
- https://github.com/code259/sprint4_frontend

### Pages
- Landing Page: Since page will be a social media website, we will have landing page to inform new visitors of the purpose of the website and to redirect to various pages.
- Home Page: After login and authentication the user will go to a home page with a list of posts by all users, of chess related topics such as certain board positions, tactics, questions, etc. User will be able to view the post and interact with the posts by having commenting capabilities, which will likely be shown in a modal. 
- Chat Page: Will have a chess board where users can interact with an Gemini or other LLM to talk and learn about chess.
- Game Page (TBD): May create a page where user can use a real chess board to play against a bot, plan on using some sort of API. 

### Tasks & Roles
Note: Groups not finalized until Add/Drop deadline. 
- Scrum Master: Nikhil Maturi
- Assistant Scrum Master: Aarush Gowda
- Developer 1: Vasanth Rajasekaran
   - Landing Page Design and Development, Javascript for Animations (GSAP)
- Developer 2: Aarush Gowda 
   - Landing Page Design and Development, UML, and Javascript for Modal Design
- Developer 3: Nikhil Maturi
   - API Calls and Upload API
- Developer 4: TBD

### Next Steps (For Checkpoint 1)
List of future ideas: https://github.com/code259/sprint4_frontend/issues/2#issue-2677357558
- [x] Create Kanban Board to track iterations and features. 
- [ ] Utilize PEP 8 Guideline for Code (https://peps.python.org/pep-0008/#introduction)
- [ ] Use UML or planning methods to show plan for integration of new ideas and features from Flocker.
- [x] Create visually appealing Homepage - create brief design using figma
- [ ] Remove redundancy in other pages and create good UX.
- [ ] Remove features from Flocker not required for our project.
- [ ] Implement API requests to LLM (AI Model), sending image data.

**Comment by jm1021** [comment]
I am not really understanding general purpose from the description.  I have found that if I don't understand most of your team members will not get what they are supposed ot work on.

Perhaps you should setup chess tournaments and have people report back on play.   Perhaps you could have individual play chess against Gemini at different levels (if capability is there).   You could have people comment on matches and talk about "strategy" you mentioned.

.88 a lot is missing from my perspective for a weeks plan.
